spring.application.name=productservice
spring.mongodb.uri=mongodb://localhost:27017/products
server.port=8080 
eureka.client.serviceUrl.defaultZone=http://eureka:password@localhost:8761/eureka


### for zipkin ui for visibility of requests and sleuth for tracing
spring.zipkin.base-url=http://localhost:9411
spring.sleuth.sampler.probability=1.0
spring.sleuth.web.client.enabled=true